dtb-$(CONFIG_ARCH_ROCKCHIP) += x3399-development-board.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += x3399-dom0-development-board.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += ibox3399-xen-domu.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
